apiVersion: apps/v1
kind: Deployment
metadata:
  name: codementor-question-deployment
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codementor-question
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: codementor-question
        tier: backend
        track: stable
        springboot: question
    spec:
      containers:
        - name: codementor-question
          image: lkh66913/codementor-question
          ports:
            - containerPort: 8080
