apiVersion: apps/v1
kind: Deployment
metadata:
  name: codementor-apigateway-deployment
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codementor-apigateway
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: codementor-apigateway
        tier: backend
        track: stable
        springboot: user
    spec:
      containers:
        - name: codementor-apigateway
          image: lkh66913/codementor-apigateway
          ports:
            - containerPort: 8080
