apiVersion: v1
kind: Service
metadata:
  name: codementor-apigateway-service
  namespace: springboot
spec:
  selector:
    app: codementor-apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
