spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://codementor-user-service
          predicates:
            - Path=/api/user/**
        - id: question-service
          uri: http://codementor-question-service
          predicates:
            - Path=/api/question/**
        - id: execute-service
          uri: http://codementor-execute-service
          predicates:
            - Path=/api/execute/**