apiVersion: v1
kind: Service
metadata:
  name: codementor-execute-service
spec:
  selector:
    app: codementor-execute
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP
