apiVersion: apps/v1
kind: Deployment
metadata:
  name: codementor-evaluation-deployment
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codementor-evaluation
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: codementor-evaluation
        tier: backend
        track: stable
        springboot: evaluation
    spec:
      containers:
        - name: codementor-evaluation
          image: lkh66913/codementor-evaluation
          ports:
            - containerPort: 8080
