apiVersion: v1
kind: Service
metadata:
  name: codementor-evaluation-service
  namespace: springboot
spec:
  selector:
    app: codementor-evaluation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
