apiVersion: v1
kind: Service
metadata:
  name: codementor-user-service
  namespace: springboot
spec:
  selector:
    app: codementor-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
