name: apigateway
on:
  push:
    branches:
      - main
      - cicd-apigateway

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./apigateway

    steps:
      # checkout 설명 https://www.daleseo.com/github-actions-checkout/
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Build with Gradle
        run: ./gradlew bootjar -x test
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Docker Image Build
        run: docker build -t lkh66913/codementor-apigateway .
        working-directory: ${{env.working-directory}}

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Push
        run: docker push lkh66913/codementor-apigateway

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with gcloud
        run: gcloud auth login --quite

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials codementor-cluster --zone us-central1-c --project invertible-spot-410007

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/codementor-apigateway-deployment codementor-apigateway=lkh66913/codementor-apigateway:latest -n springboot
